import type { NextPage } from 'next'
import Head from 'next/head'
import Main from '../Components/Main'
import Skills from '../Components/Skills'
import Education from '../Components/Education'
import Experience from '../Components/Experience'
import Hobbies from '../Components/Hobbies'

const Home: NextPage = () => {
  return (
    <div className={`container`}>
      <Head>
        <title>Kamontip&apos;s</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main/>
      <Education/>
      <Skills/>
      <Experience/>
      <Hobbies/>
    </div>
  )
}

export default Home
